<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_IN 91_cvf_phone_num</name>
   <tag></tag>
   <elementGuidId>2d61efa6-c665-4374-8bc1-de5d33a239a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='cvf_phone_num']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;cvf_phone_num&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>84ce5339-45fc-4ed7-87c4-46b17f8e86a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>fab4e596-e376-4de6-b08d-f97f850c390e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>3feab2d0-2937-4912-b157-14d2d93776b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cvf_phone_num</value>
      <webElementGuid>30d47844-d502-461f-a5ed-5ca345de45cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-input-text a-span12 cvf-widget-input</value>
      <webElementGuid>5e7d7b02-29e4-487c-95be-944ac09d6dee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cvf-page-content&quot;)/div[@class=&quot;a-box&quot;]/div[@class=&quot;a-box-inner a-padding-extra-large&quot;]/div[@class=&quot;a-row&quot;]/form[@class=&quot;cvf-widget-form a-spacing-none&quot;]/div[@class=&quot;a-row a-spacing-base&quot;]/div[@class=&quot;a-row a-grid-vertical-align a-grid-top&quot;]/div[@class=&quot;a-fixed-left-grid a-spacing-top-mini&quot;]/div[@class=&quot;a-fixed-left-grid-inner&quot;]/div[@class=&quot;a-fixed-left-grid-col a-col-right&quot;]/input[@class=&quot;a-input-text a-span12 cvf-widget-input&quot;]</value>
      <webElementGuid>66237c4f-2a28-45cc-974a-ea8b88ba3e42</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='cvf_phone_num']</value>
      <webElementGuid>fb47648c-2970-49d8-a48a-5685121619f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cvf-page-content']/div/div/div/form/div/div/div[2]/div/div[2]/input</value>
      <webElementGuid>c2e4dbfd-bdef-4cbe-94c3-218865ec896a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>2207b6bf-73f5-4ef4-ba5f-4e453459f621</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @name = 'cvf_phone_num']</value>
      <webElementGuid>b9b463b1-881f-4072-aa45-b8c6aab3fad5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
